const initialState = {
  tilesStatus: {
    tile1: "empty",
    tile2: "empty",
    tile3: "empty",
    tile4: "empty",
    tile5: "empty",
    tile6: "empty",
    tile7: "empty",
    tile8: "empty",
    tile9: "empty",
    tile10: "empty",
    tile11: "empty",
    tile12: "empty",
    tile13: "empty",
    tile14: "empty",
    tile15: "empty",
    tile16: "empty",
    tile17: "empty",
    tile18: "empty",
    tile19: "empty",
    tile20: "empty",
    tile21: "empty",
    tile22: "empty",
    tile23: "empty",
    tile24: "empty",
    tile25: "empty",
    tile26: "empty",
    tile27: "empty",
    tile28: "empty",
    tile29: "empty",
    tile30: "empty",
    tile31: "empty",
    tile32: "empty",
    tile33: "empty",
    tile34: "empty",
    tile35: "empty",
    tile36: "empty",
    tile37: "empty",
    tile38: "empty",
    tile39: "empty",
    tile40: "empty",
    tile41: "empty",
    tile42: "empty",
    tile43: "empty",
    tile44: "empty",
    tile45: "empty",
    tile46: "empty",
    tile47: "empty",
    tile48: "empty",
    tile49: "empty",
    tile50: "empty",
    tile51: "empty",
    tile52: "empty",
    tile53: "empty",
    tile54: "empty",
    tile55: "empty",
    tile56: "empty",
    tile57: "empty",
    tile58: "empty",
    tile59: "empty",
    tile60: "empty",
    tile61: "empty",
    tile62: "empty",
    tile63: "empty",
    tile64: "empty",
    tile65: "empty",
    tile66: "empty",
    tile67: "empty",
    tile68: "empty",
    tile69: "empty",
    tile70: "empty",
    tile71: "empty",
    tile72: "empty",
    tile73: "empty",
    tile74: "empty",
    tile75: "empty",
    tile76: "empty",
    tile77: "empty",
    tile78: "empty",
    tile79: "empty",
    tile80: "empty",
    tile81: "empty",
    tile82: "empty",
    tile83: "empty",
    tile84: "empty",
    tile85: "empty",
    tile86: "empty",
    tile87: "empty",
    tile88: "empty",
    tile89: "empty",
    tile90: "empty",
    tile91: "empty",
    tile92: "empty",
    tile93: "empty",
    tile94: "empty",
    tile95: "empty",
    tile96: "empty",
    tile97: "empty",
    tile98: "empty",
    tile99: "empty",
    tile100: "empty"
  }
};

const reducer = (state = initialState, action) => {
  switch (action.type) {
    case "FILL_TILE":
      const tileKey = action.key;
      const { tilesStatus } = state;
      tilesStatus[`tile${tileKey}`] = "full";

      return {
        ...state,
        tilesStatus
      };
    default:
      break;
  }
};

export default reducer;
